modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="morearmor"
version="1.0.0"
displayName="More Armor"
authors="Elijah Farrell"
credits="Armor textures: averagertateman"
logoFile="assets/morearmor/MoreArmorLogo.png"
description='''
A Minecraft Forge mod that adds various vanilla-style and custom armor sets.
'''